import { CSSProperties } from "react";


const styles: { [key: string]: CSSProperties } = {
    container: {
      minHeight: '100vh',
      backgroundColor: '#1a1a1a',
      color: '#ffffff',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '16px 40px',
      borderBottom: '1px solid #2a2a2a',
    },
    headerLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
    },
    logo: {
      fontSize: '24px',
    },
    brandName: {
      fontSize: '18px',
      fontWeight: '600',
    },
    headerRight: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    },
    username: {
      fontSize: '14px',
      color: '#e0e0e0',
    },
    avatar: {
      width: '40px',
      height: '40px',
      borderRadius: '50%',
      backgroundColor: '#0066ff',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '14px',
      fontWeight: '600',
      border: '2px solid #0066ff',
    },
    main: {
      padding: '24px 40px',
    },
    topBar: {
      marginBottom: '32px',
    },
    tabSection: {
      marginBottom: '20px',
    },
    activeTab: {
      background: 'none',
      border: 'none',
      color: '#ffffff',
      fontSize: '16px',
      fontWeight: '600',
      padding: '0 0 8px 0',
      borderBottom: '3px solid #0066ff',
      cursor: 'pointer',
    },
    searchSection: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: '16px',
    },
    searchBox: {
      flex: 1,
      maxWidth: '400px',
      position: 'relative',
      display: 'flex',
      alignItems: 'center',
    },
    searchIcon: {
      position: 'absolute',
      left: '16px',
      fontSize: '16px',
    },
    searchInput: {
      width: '100%',
      padding: '12px 16px 12px 44px',
      backgroundColor: '#2a2a2a',
      border: '1px solid #3a3a3a',
      borderRadius: '8px',
      color: '#ffffff',
      fontSize: '14px',
      outline: 'none',
    },
    createButton: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      padding: '12px 24px',
      backgroundColor: '#22c55e',
      color: '#ffffff',
      border: 'none',
      borderRadius: '8px',
      fontSize: '14px',
      fontWeight: '600',
      cursor: 'pointer',
      whiteSpace: 'nowrap',
    },
    buttonIcon: {
      fontSize: '16px',
    },
    spacesGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
      gap: '20px',
    },
    spaceCard: {
      backgroundColor: '#2a2a2a',
      borderRadius: '12px',
      padding: '20px',
      cursor: 'pointer',
      transition: 'background-color 0.2s',
    },
    spaceTitle: {
      fontSize: '16px',
      fontWeight: '500',
      margin: '0 0 16px 0',
      lineHeight: '1.4',
    },
    spaceFooter: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
    },
    participants: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
    },
    participantInfo: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    participantAvatar: {
      width: '32px',
      height: '32px',
      borderRadius: '50%',
      backgroundColor: '#4a4a4a',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '11px',
      fontWeight: '600',
      flexShrink: 0,
    },
    participantDetails: {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
    },
    participantName: {
      fontSize: '13px',
      color: '#e0e0e0',
    },
    speakerBadge: {
      fontSize: '12px',
    },
    memberCount: {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
      fontSize: '14px',
      color: '#b0b0b0',
    },
    memberIcon: {
      fontSize: '14px',
    },
    modalOverlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000,
      padding: '20px',
    },
    modal: {
      backgroundColor: '#2a2a2a',
      borderRadius: '16px',
      padding: '32px',
      maxWidth: '600px',
      width: '100%',
      maxHeight: '90vh',
      overflowY: 'auto',
      position: 'relative',
    },
    closeButton: {
      position: 'absolute',
      top: '16px',
      right: '16px',
      background: 'none',
      border: 'none',
      color: '#b0b0b0',
      fontSize: '24px',
      cursor: 'pointer',
      padding: '4px',
      lineHeight: 1,
    },
    modalTitle: {
      fontSize: '24px',
      fontWeight: '600',
      margin: '0 0 24px 0',
    },
    formGroup: {
      marginBottom: '24px',
    },
    label: {
      display: 'block',
      fontSize: '14px',
      fontWeight: '500',
      marginBottom: '8px',
      color: '#e0e0e0',
    },
    input: {
      width: '100%',
      padding: '12px 16px',
      backgroundColor: '#1a1a1a',
      border: '1px solid #3a3a3a',
      borderRadius: '8px',
      color: '#ffffff',
      fontSize: '15px',
      outline: 'none',
      boxSizing: 'border-box',
    },
    dimensionsRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    },
    dimensionInput: {
      flex: 1,
      padding: '12px 16px',
      backgroundColor: '#1a1a1a',
      border: '1px solid #3a3a3a',
      borderRadius: '8px',
      color: '#ffffff',
      fontSize: '15px',
      outline: 'none',
    },
    dimensionSeparator: {
      fontSize: '20px',
      color: '#666',
    },
    dimensionNote: {
      fontSize: '12px',
      color: '#808080',
      margin: '8px 0 0 0',
    },
    selectMapButton: {
      width: '100%',
      padding: '12px 16px',
      backgroundColor: '#3a3a3a',
      border: '1px solid #4a4a4a',
      borderRadius: '8px',
      color: '#ffffff',
      fontSize: '14px',
      cursor: 'pointer',
      fontWeight: '500',
    },
    selectedMapCard: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      padding: '12px',
      backgroundColor: '#1a1a1a',
      border: '2px solid #0066ff',
      borderRadius: '8px',
    },
    selectedMapThumbnail: {
      width: '60px',
      height: '40px',
      borderRadius: '6px',
      objectFit: 'cover',
    },
    selectedMapInfo: {
      flex: 1,
    },
    selectedMapName: {
      fontSize: '14px',
      fontWeight: '500',
      margin: '0 0 4px 0',
    },
    selectedMapDimensions: {
      fontSize: '12px',
      color: '#808080',
      margin: 0,
    },
    changeMapButton: {
      padding: '8px 16px',
      backgroundColor: '#3a3a3a',
      border: 'none',
      borderRadius: '6px',
      color: '#ffffff',
      fontSize: '13px',
      cursor: 'pointer',
      fontWeight: '500',
    },
    mapSelector: {
      marginTop: '16px',
      padding: '16px',
      backgroundColor: '#1a1a1a',
      borderRadius: '8px',
    },
    mapSelectorTitle: {
      fontSize: '16px',
      fontWeight: '600',
      margin: '0 0 16px 0',
    },
    noneMapCard: {
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      padding: '12px',
      backgroundColor: '#2a2a2a',
      border: '2px solid #3a3a3a',
      borderRadius: '8px',
      cursor: 'pointer',
      marginBottom: '16px',
      textAlign: 'left',
    },
    noneMapIcon: {
      fontSize: '32px',
      width: '60px',
      height: '40px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#3a3a3a',
      borderRadius: '6px',
    },
    noneMapText: {
      flex: 1,
    },
    mapGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '12px',
    },
    mapCard: {
      display: 'flex',
      flexDirection: 'column',
      padding: '12px',
      backgroundColor: '#2a2a2a',
      border: '2px solid #3a3a3a',
      borderRadius: '8px',
      cursor: 'pointer',
      textAlign: 'left',
    },
    mapThumbnail: {
      width: '100%',
      height: '80px',
      borderRadius: '6px',
      objectFit: 'cover',
      marginBottom: '8px',
    },
    mapInfo: {
      flex: 1,
    },
    mapName: {
      fontSize: '14px',
      fontWeight: '500',
      margin: '0 0 4px 0',
      color: '#ffffff',
    },
    mapDimensions: {
      fontSize: '12px',
      color: '#808080',
      margin: 0,
    },
    createSpaceButton: {
      width: '100%',
      padding: '14px 24px',
      backgroundColor: '#22c55e',
      color: '#ffffff',
      border: 'none',
      borderRadius: '8px',
      fontSize: '16px',
      fontWeight: '600',
      cursor: 'pointer',
    }}


    export default styles;